# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b10d721b754bce1175d01c591d3b8574f1b3674149278b006d73072e50114605584234a6eccc592d6c2ee911f0e1f667bc00955f13c2b5a56f5f156ac623aec1

test:
  secret_key_base: 385c167181a397f269472da910aa2110f3fcf2a4da2fe87c10be8d7d6ca343e54da06d39cffe0de7f3b915ae899734ff1c50f232f8a5c65d3a34c7e76c39493e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
